################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C++M_SRCS := 
C++_SRCS := 
CCM_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXXM_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
C++M_DEPS := 
C++_DEPS := 
CCM_DEPS := 
CC_DEPS := 
CPP_DEPS := 
CXXM_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
.metadata/.plugins/org.eclipse.cdt.make.core \
bindings/python \
build-support \
cmake-cache/CMakeFiles/3.22.1/CompilerIdC \
cmake-cache/CMakeFiles/3.22.1/CompilerIdCXX \
cmake-cache/CMakeFiles/CheckTypeSize \
cmake-cache/CMakeFiles/stdlib_pch.dir/build-support \
cmake-cache/CMakeFiles/stdlib_pch.dir \
cmake-cache/CMakeFiles/stdlib_pch_exec.dir/build-support \
cmake-cache/CMakeFiles/stdlib_pch_exec.dir \
cmake-cache/contrib/ns3-ai/CMakeFiles/libns3-ai-obj.dir/model \
cmake-cache/scratch/CMakeFiles/scratch_a_plus_b_sim.dir/a_plus_b \
cmake-cache/scratch/CMakeFiles/scratch_escenarios_estudio_escenario1.dir/escenarios_estudio \
cmake-cache/scratch/CMakeFiles/scratch_first.dir \
cmake-cache/scratch/CMakeFiles/scratch_ns3ai-data-collection_sim2.dir/ns3ai-data-collection \
cmake-cache/scratch/CMakeFiles/scratch_scratch-simulator.dir \
cmake-cache/scratch/CMakeFiles/scratch_subdir_scratch-simulator-subdir.dir/subdir \
cmake-cache/scratch/CMakeFiles/scratch_wifi-ap-flowmonitor.dir \
cmake-cache/scratch/CMakeFiles/scratch_wifi-ap-modified.dir \
cmake-cache/scratch/CMakeFiles/scratch_wifi-ap.dir \
cmake-cache/src/antenna/CMakeFiles/libantenna-obj.dir/model \
cmake-cache/src/aodv/CMakeFiles/libaodv-obj.dir/helper \
cmake-cache/src/aodv/CMakeFiles/libaodv-obj.dir/model \
cmake-cache/src/applications/CMakeFiles/libapplications-obj.dir/helper \
cmake-cache/src/applications/CMakeFiles/libapplications-obj.dir/model \
cmake-cache/src/bridge/CMakeFiles/libbridge-obj.dir/helper \
cmake-cache/src/bridge/CMakeFiles/libbridge-obj.dir/model \
cmake-cache/src/buildings/CMakeFiles/libbuildings-obj.dir/helper \
cmake-cache/src/buildings/CMakeFiles/libbuildings-obj.dir/model \
cmake-cache/src/config-store/CMakeFiles/libconfig-store-obj.dir/model \
cmake-cache/src/core/CMakeFiles/libcore-obj.dir/helper \
cmake-cache/src/core/CMakeFiles/libcore-obj.dir/model \
cmake-cache/src/csma/CMakeFiles/libcsma-obj.dir/helper \
cmake-cache/src/csma/CMakeFiles/libcsma-obj.dir/model \
cmake-cache/src/csma-layout/CMakeFiles/libcsma-layout-obj.dir/model \
cmake-cache/src/dsdv/CMakeFiles/libdsdv-obj.dir/helper \
cmake-cache/src/dsdv/CMakeFiles/libdsdv-obj.dir/model \
cmake-cache/src/dsr/CMakeFiles/libdsr-obj.dir/helper \
cmake-cache/src/dsr/CMakeFiles/libdsr-obj.dir/model \
cmake-cache/src/energy/CMakeFiles/libenergy-obj.dir/helper \
cmake-cache/src/energy/CMakeFiles/libenergy-obj.dir/model \
cmake-cache/src/fd-net-device/CMakeFiles/libfd-net-device-obj.dir/helper \
cmake-cache/src/fd-net-device/CMakeFiles/libfd-net-device-obj.dir/model \
cmake-cache/src/fd-net-device/CMakeFiles/raw-sock-creator.dir/helper \
cmake-cache/src/fd-net-device/CMakeFiles/tap-device-creator.dir/helper \
cmake-cache/src/flow-monitor/CMakeFiles/libflow-monitor-obj.dir/helper \
cmake-cache/src/flow-monitor/CMakeFiles/libflow-monitor-obj.dir/model \
cmake-cache/src/internet/CMakeFiles/libinternet-obj.dir/helper \
cmake-cache/src/internet/CMakeFiles/libinternet-obj.dir/model \
cmake-cache/src/internet-apps/CMakeFiles/libinternet-apps-obj.dir/helper \
cmake-cache/src/internet-apps/CMakeFiles/libinternet-apps-obj.dir/model \
cmake-cache/src/lr-wpan/CMakeFiles/liblr-wpan-obj.dir/helper \
cmake-cache/src/lr-wpan/CMakeFiles/liblr-wpan-obj.dir/model \
cmake-cache/src/lte/CMakeFiles/liblte-obj.dir/helper \
cmake-cache/src/lte/CMakeFiles/liblte-obj.dir/model \
cmake-cache/src/mesh/CMakeFiles/libmesh-obj.dir/helper/dot11s \
cmake-cache/src/mesh/CMakeFiles/libmesh-obj.dir/helper/flame \
cmake-cache/src/mesh/CMakeFiles/libmesh-obj.dir/helper \
cmake-cache/src/mesh/CMakeFiles/libmesh-obj.dir/model/dot11s \
cmake-cache/src/mesh/CMakeFiles/libmesh-obj.dir/model/flame \
cmake-cache/src/mesh/CMakeFiles/libmesh-obj.dir/model \
cmake-cache/src/mobility/CMakeFiles/libmobility-obj.dir/helper \
cmake-cache/src/mobility/CMakeFiles/libmobility-obj.dir/model \
cmake-cache/src/netanim/CMakeFiles/libnetanim-obj.dir/model \
cmake-cache/src/network/CMakeFiles/libnetwork-obj.dir/helper \
cmake-cache/src/network/CMakeFiles/libnetwork-obj.dir/model \
cmake-cache/src/network/CMakeFiles/libnetwork-obj.dir/utils \
cmake-cache/src/nix-vector-routing/CMakeFiles/libnix-vector-routing-obj.dir/helper \
cmake-cache/src/nix-vector-routing/CMakeFiles/libnix-vector-routing-obj.dir/model \
cmake-cache/src/olsr/CMakeFiles/libolsr-obj.dir/helper \
cmake-cache/src/olsr/CMakeFiles/libolsr-obj.dir/model \
cmake-cache/src/point-to-point/CMakeFiles/libpoint-to-point-obj.dir/helper \
cmake-cache/src/point-to-point/CMakeFiles/libpoint-to-point-obj.dir/model \
cmake-cache/src/point-to-point-layout/CMakeFiles/libpoint-to-point-layout-obj.dir/model \
cmake-cache/src/propagation/CMakeFiles/libpropagation-obj.dir/model \
cmake-cache/src/sixlowpan/CMakeFiles/libsixlowpan-obj.dir/helper \
cmake-cache/src/sixlowpan/CMakeFiles/libsixlowpan-obj.dir/model \
cmake-cache/src/spectrum/CMakeFiles/libspectrum-obj.dir/helper \
cmake-cache/src/spectrum/CMakeFiles/libspectrum-obj.dir/model \
cmake-cache/src/stats/CMakeFiles/libstats-obj.dir/helper \
cmake-cache/src/stats/CMakeFiles/libstats-obj.dir/model \
cmake-cache/src/tap-bridge/CMakeFiles/libtap-bridge-obj.dir/helper \
cmake-cache/src/tap-bridge/CMakeFiles/libtap-bridge-obj.dir/model \
cmake-cache/src/tap-bridge/CMakeFiles/tap-creator.dir/model \
cmake-cache/src/test/CMakeFiles/libtest.dir/__/__/build-support \
cmake-cache/src/test/CMakeFiles/libtest.dir \
cmake-cache/src/test/CMakeFiles/libtest.dir/ns3tc \
cmake-cache/src/test/CMakeFiles/libtest.dir/ns3tcp \
cmake-cache/src/test/CMakeFiles/libtest.dir/ns3wifi \
cmake-cache/src/test/CMakeFiles/libtest.dir/traced \
cmake-cache/src/topology-read/CMakeFiles/libtopology-read-obj.dir/helper \
cmake-cache/src/topology-read/CMakeFiles/libtopology-read-obj.dir/model \
cmake-cache/src/traffic-control/CMakeFiles/libtraffic-control-obj.dir/helper \
cmake-cache/src/traffic-control/CMakeFiles/libtraffic-control-obj.dir/model \
cmake-cache/src/uan/CMakeFiles/libuan-obj.dir/helper \
cmake-cache/src/uan/CMakeFiles/libuan-obj.dir/model \
cmake-cache/src/virtual-net-device/CMakeFiles/libvirtual-net-device-obj.dir/model \
cmake-cache/src/wave/CMakeFiles/libwave-obj.dir/helper \
cmake-cache/src/wave/CMakeFiles/libwave-obj.dir/model \
cmake-cache/src/wifi/CMakeFiles/libwifi-obj.dir/helper \
cmake-cache/src/wifi/CMakeFiles/libwifi-obj.dir/model \
cmake-cache/src/wifi/CMakeFiles/libwifi-obj.dir/model/he \
cmake-cache/src/wifi/CMakeFiles/libwifi-obj.dir/model/ht \
cmake-cache/src/wifi/CMakeFiles/libwifi-obj.dir/model/non-ht \
cmake-cache/src/wifi/CMakeFiles/libwifi-obj.dir/model/rate-control \
cmake-cache/src/wifi/CMakeFiles/libwifi-obj.dir/model/vht \
cmake-cache/src/wimax/CMakeFiles/libwimax-obj.dir/helper \
cmake-cache/src/wimax/CMakeFiles/libwimax-obj.dir/model \
cmake-cache/utils/CMakeFiles/bench-packets.dir \
cmake-cache/utils/CMakeFiles/bench-simulator.dir \
cmake-cache/utils/CMakeFiles/perf-io.dir/perf \
cmake-cache/utils/CMakeFiles/print-introspected-doxygen.dir \
contrib/ns3-ai/examples/a_plus_b \
contrib/ns3-ai/examples/interference-pattern \
contrib/ns3-ai/examples/lte_cqi \
contrib/ns3-ai/examples/q-tcp \
contrib/ns3-ai/examples/rate-control \
contrib/ns3-ai/examples/rl-tcp \
contrib/ns3-ai/examples \
contrib/ns3-ai/model \
contrib/ns3-ai/py_interface/build/temp.linux-x86_64-3.10 \
contrib/ns3-ai/py_interface \
examples/channel-models \
examples/energy \
examples/error-model \
examples/ipv6 \
examples/matrix-topology \
examples/naming \
examples/realtime \
examples/routing \
examples/socket \
examples/stats \
examples/tcp \
examples/traffic-control \
examples/tutorial \
examples/udp \
examples/udp-client-server \
examples/wireless \
old_scripts \
scratch/a_plus_b \
scratch/escenarios_estudio \
scratch \
scratch/ns3ai-data-collection \
scratch/subdir \
src/antenna/model \
src/antenna/test \
src/aodv/examples \
src/aodv/helper \
src/aodv/model \
src/aodv/test \
src/applications/examples \
src/applications/helper \
src/applications/model \
src/applications/test \
src/bridge/examples \
src/bridge/helper \
src/bridge/model \
src/brite/examples \
src/brite/helper \
src/brite/test \
src/buildings/examples \
src/buildings/helper \
src/buildings/model \
src/buildings/test \
src/click/examples \
src/click/helper \
src/click/model \
src/click/test \
src/config-store/examples \
src/config-store/model \
src/core/bindings \
src/core/examples \
src/core/helper \
src/core/model \
src/core/test \
src/csma/examples \
src/csma/helper \
src/csma/model \
src/csma-layout/examples \
src/csma-layout/model \
src/dsdv/examples \
src/dsdv/helper \
src/dsdv/model \
src/dsdv/test \
src/dsr/examples \
src/dsr/helper \
src/dsr/model \
src/dsr/test \
src/energy/examples \
src/energy/helper \
src/energy/model \
src/energy/test \
src/fd-net-device/examples \
src/fd-net-device/helper \
src/fd-net-device/model \
src/flow-monitor/helper \
src/flow-monitor/model \
src/internet/examples \
src/internet/helper \
src/internet/model \
src/internet/test \
src/internet-apps/examples \
src/internet-apps/helper \
src/internet-apps/model \
src/internet-apps/test \
src/lr-wpan/examples \
src/lr-wpan/helper \
src/lr-wpan/model \
src/lr-wpan/test \
src/lte/examples \
src/lte/helper \
src/lte/model \
src/lte/test \
src/mesh/examples \
src/mesh/helper/dot11s \
src/mesh/helper/flame \
src/mesh/helper \
src/mesh/model/dot11s \
src/mesh/model/flame \
src/mesh/model \
src/mesh/test/dot11s \
src/mesh/test/flame \
src/mesh/test \
src/mobility/examples \
src/mobility/helper \
src/mobility/model \
src/mobility/test \
src/mpi/examples \
src/mpi/model \
src/mpi/test \
src/netanim/examples \
src/netanim/model \
src/netanim/test \
src/network/examples \
src/network/helper \
src/network/model \
src/network/test \
src/network/utils \
src/nix-vector-routing/examples \
src/nix-vector-routing/helper \
src/nix-vector-routing/model \
src/nix-vector-routing/test \
src/olsr/examples \
src/olsr/helper \
src/olsr/model \
src/olsr/test \
src/openflow/examples \
src/openflow/helper \
src/openflow/model \
src/openflow/test \
src/point-to-point/examples \
src/point-to-point/helper \
src/point-to-point/model \
src/point-to-point/test \
src/point-to-point-layout/model \
src/propagation/examples \
src/propagation/model \
src/propagation/test \
src/sixlowpan/examples \
src/sixlowpan/helper \
src/sixlowpan/model \
src/sixlowpan/test \
src/spectrum/examples \
src/spectrum/helper \
src/spectrum/model \
src/spectrum/test \
src/stats/examples \
src/stats/helper \
src/stats/model \
src/stats/test \
src/tap-bridge/examples \
src/tap-bridge/helper \
src/tap-bridge/model \
src/test \
src/test/ns3tc \
src/test/ns3tcp \
src/test/ns3wifi \
src/test/traced \
src/topology-read/examples \
src/topology-read/helper \
src/topology-read/model \
src/topology-read/test \
src/traffic-control/examples \
src/traffic-control/helper \
src/traffic-control/model \
src/traffic-control/test \
src/uan/examples \
src/uan/helper \
src/uan/model \
src/uan/test \
src/virtual-net-device/examples \
src/virtual-net-device/model \
src/visualizer/model \
src/wave/examples \
src/wave/helper \
src/wave/model \
src/wave/test \
src/wifi/examples \
src/wifi/helper \
src/wifi/model \
src/wifi/model/he \
src/wifi/model/ht \
src/wifi/model/non-ht \
src/wifi/model/rate-control \
src/wifi/model/vht \
src/wifi/test \
src/wimax/examples \
src/wimax/helper \
src/wimax/model \
src/wimax/test \
utils \
utils/perf \

